project:
  type: website

website:
  title: "NADAS"
  navbar:
    logo: "images/Logo_NADAS.png"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/NADAS-network/homepage
          - text: Report a Bug
            url:  https://github.com/NADAS-network/homepage/issues
    right:
      - href: index.qmd
        text: Home
      - text: "About us"
        menu:
        - href: funding.qmd
          text: Funding body
        - href: institutions.qmd
          text: Participating institutions
        - href: team.qmd
          text: Team members
      - href: posts.qmd
        text: Archive

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


